mem={}

def checkres(res):
    if res in mem:
        print(res)
        exit(0)
    else:
        mem[res] = 1


res = 0
while True:
    res=res+16
    checkres(res)
    res=res+9
    checkres(res)
    res=res+11
    checkres(res)
    res=res+13
    checkres(res)
    res=res+11
    checkres(res)
    res=res+3
    checkres(res)
    res=res+8
    checkres(res)
    res=res+9
    checkres(res)
    res=res+14
    checkres(res)
    res=res+16
    checkres(res)
    res=res-5
    checkres(res)
    res=res-15
    checkres(res)
    res=res+5
    checkres(res)
    res=res-7
    checkres(res)
    res=res-5
    checkres(res)
    res=res-18
    checkres(res)
    res=res-9
    checkres(res)
    res=res+2
    checkres(res)
    res=res+1
    checkres(res)
    res=res+18
    checkres(res)
    res=res+15
    checkres(res)
    res=res+6
    checkres(res)
    res=res+19
    checkres(res)
    res=res-9
    checkres(res)
    res=res+1
    checkres(res)
    res=res+15
    checkres(res)
    res=res-10
    checkres(res)
    res=res-3
    checkres(res)
    res=res-18
    checkres(res)
    res=res+7
    checkres(res)
    res=res-1
    checkres(res)
    res=res+7
    checkres(res)
    res=res+6
    checkres(res)
    res=res+13
    checkres(res)
    res=res+10
    checkres(res)
    res=res+10
    checkres(res)
    res=res+9
    checkres(res)
    res=res+18
    checkres(res)
    res=res+2
    checkres(res)
    res=res+15
    checkres(res)
    res=res-19
    checkres(res)
    res=res+13
    checkres(res)
    res=res+8
    checkres(res)
    res=res-18
    checkres(res)
    res=res+6
    checkres(res)
    res=res-12
    checkres(res)
    res=res+10
    checkres(res)
    res=res+5
    checkres(res)
    res=res-6
    checkres(res)
    res=res+14
    checkres(res)
    res=res+8
    checkres(res)
    res=res+2
    checkres(res)
    res=res+2
    checkres(res)
    res=res+12
    checkres(res)
    res=res-2
    checkres(res)
    res=res+5
    checkres(res)
    res=res-11
    checkres(res)
    res=res-2
    checkres(res)
    res=res+7
    checkres(res)
    res=res+7
    checkres(res)
    res=res-19
    checkres(res)
    res=res-6
    checkres(res)
    res=res-1
    checkres(res)
    res=res-12
    checkres(res)
    res=res+16
    checkres(res)
    res=res-2
    checkres(res)
    res=res+13
    checkres(res)
    res=res+17
    checkres(res)
    res=res+15
    checkres(res)
    res=res-9
    checkres(res)
    res=res+3
    checkres(res)
    res=res+16
    checkres(res)
    res=res+13
    checkres(res)
    res=res+14
    checkres(res)
    res=res+17
    checkres(res)
    res=res-10
    checkres(res)
    res=res+1
    checkres(res)
    res=res+3
    checkres(res)
    res=res+10
    checkres(res)
    res=res-18
    checkres(res)
    res=res-1
    checkres(res)
    res=res-15
    checkres(res)
    res=res+5
    checkres(res)
    res=res-16
    checkres(res)
    res=res-7
    checkres(res)
    res=res-9
    checkres(res)
    res=res+18
    checkres(res)
    res=res+17
    checkres(res)
    res=res+3
    checkres(res)
    res=res+8
    checkres(res)
    res=res+7
    checkres(res)
    res=res-3
    checkres(res)
    res=res-11
    checkres(res)
    res=res-19
    checkres(res)
    res=res-8
    checkres(res)
    res=res-10
    checkres(res)
    res=res-11
    checkres(res)
    res=res-5
    checkres(res)
    res=res-1
    checkres(res)
    res=res+19
    checkres(res)
    res=res-8
    checkres(res)
    res=res-9
    checkres(res)
    res=res+11
    checkres(res)
    res=res+16
    checkres(res)
    res=res+11
    checkres(res)
    res=res+3
    checkres(res)
    res=res+17
    checkres(res)
    res=res+14
    checkres(res)
    res=res+9
    checkres(res)
    res=res+15
    checkres(res)
    res=res+7
    checkres(res)
    res=res-15
    checkres(res)
    res=res+16
    checkres(res)
    res=res+6
    checkres(res)
    res=res-2
    checkres(res)
    res=res+13
    checkres(res)
    res=res+5
    checkres(res)
    res=res+16
    checkres(res)
    res=res-6
    checkres(res)
    res=res-3
    checkres(res)
    res=res+7
    checkres(res)
    res=res+10
    checkres(res)
    res=res-4
    checkres(res)
    res=res-18
    checkres(res)
    res=res+16
    checkres(res)
    res=res-6
    checkres(res)
    res=res-1
    checkres(res)
    res=res-18
    checkres(res)
    res=res-3
    checkres(res)
    res=res+13
    checkres(res)
    res=res-18
    checkres(res)
    res=res-10
    checkres(res)
    res=res+19
    checkres(res)
    res=res-13
    checkres(res)
    res=res+20
    checkres(res)
    res=res-10
    checkres(res)
    res=res-17
    checkres(res)
    res=res-10
    checkres(res)
    res=res-1
    checkres(res)
    res=res+10
    checkres(res)
    res=res-8
    checkres(res)
    res=res-15
    checkres(res)
    res=res+4
    checkres(res)
    res=res+18
    checkres(res)
    res=res-16
    checkres(res)
    res=res-13
    checkres(res)
    res=res-15
    checkres(res)
    res=res-8
    checkres(res)
    res=res+4
    checkres(res)
    res=res-6
    checkres(res)
    res=res-14
    checkres(res)
    res=res+4
    checkres(res)
    res=res-22
    checkres(res)
    res=res-9
    checkres(res)
    res=res-6
    checkres(res)
    res=res+9
    checkres(res)
    res=res-4
    checkres(res)
    res=res-16
    checkres(res)
    res=res+19
    checkres(res)
    res=res-25
    checkres(res)
    res=res+12
    checkres(res)
    res=res-10
    checkres(res)
    res=res-21
    checkres(res)
    res=res-3
    checkres(res)
    res=res-6
    checkres(res)
    res=res-4
    checkres(res)
    res=res+16
    checkres(res)
    res=res-21
    checkres(res)
    res=res-17
    checkres(res)
    res=res+13
    checkres(res)
    res=res-10
    checkres(res)
    res=res-8
    checkres(res)
    res=res+6
    checkres(res)
    res=res-19
    checkres(res)
    res=res+15
    checkres(res)
    res=res+17
    checkres(res)
    res=res-5
    checkres(res)
    res=res+3
    checkres(res)
    res=res-8
    checkres(res)
    res=res-12
    checkres(res)
    res=res-11
    checkres(res)
    res=res-14
    checkres(res)
    res=res+16
    checkres(res)
    res=res-6
    checkres(res)
    res=res-11
    checkres(res)
    res=res+8
    checkres(res)
    res=res+19
    checkres(res)
    res=res-9
    checkres(res)
    res=res+7
    checkres(res)
    res=res-21
    checkres(res)
    res=res-22
    checkres(res)
    res=res+4
    checkres(res)
    res=res-10
    checkres(res)
    res=res-2
    checkres(res)
    res=res-11
    checkres(res)
    res=res-10
    checkres(res)
    res=res-2
    checkres(res)
    res=res+19
    checkres(res)
    res=res+18
    checkres(res)
    res=res+10
    checkres(res)
    res=res+5
    checkres(res)
    res=res+3
    checkres(res)
    res=res+7
    checkres(res)
    res=res+1
    checkres(res)
    res=res+10
    checkres(res)
    res=res+4
    checkres(res)
    res=res-6
    checkres(res)
    res=res+23
    checkres(res)
    res=res-5
    checkres(res)
    res=res+4
    checkres(res)
    res=res+10
    checkres(res)
    res=res-12
    checkres(res)
    res=res+21
    checkres(res)
    res=res+7
    checkres(res)
    res=res-20
    checkres(res)
    res=res+3
    checkres(res)
    res=res+29
    checkres(res)
    res=res-11
    checkres(res)
    res=res-22
    checkres(res)
    res=res-16
    checkres(res)
    res=res-1
    checkres(res)
    res=res-9
    checkres(res)
    res=res-4
    checkres(res)
    res=res+22
    checkres(res)
    res=res-29
    checkres(res)
    res=res-5
    checkres(res)
    res=res-2
    checkres(res)
    res=res-24
    checkres(res)
    res=res-9
    checkres(res)
    res=res-13
    checkres(res)
    res=res-10
    checkres(res)
    res=res-16
    checkres(res)
    res=res-15
    checkres(res)
    res=res-18
    checkres(res)
    res=res+13
    checkres(res)
    res=res-2
    checkres(res)
    res=res-12
    checkres(res)
    res=res-3
    checkres(res)
    res=res-16
    checkres(res)
    res=res-9
    checkres(res)
    res=res-6
    checkres(res)
    res=res-3
    checkres(res)
    res=res-7
    checkres(res)
    res=res-18
    checkres(res)
    res=res-16
    checkres(res)
    res=res-12
    checkres(res)
    res=res-9
    checkres(res)
    res=res-19
    checkres(res)
    res=res-5
    checkres(res)
    res=res-11
    checkres(res)
    res=res+1
    checkres(res)
    res=res-5
    checkres(res)
    res=res-4
    checkres(res)
    res=res-11
    checkres(res)
    res=res-7
    checkres(res)
    res=res+15
    checkres(res)
    res=res+5
    checkres(res)
    res=res-3
    checkres(res)
    res=res+2
    checkres(res)
    res=res+16
    checkres(res)
    res=res-6
    checkres(res)
    res=res+15
    checkres(res)
    res=res-6
    checkres(res)
    res=res+9
    checkres(res)
    res=res-13
    checkres(res)
    res=res+21
    checkres(res)
    res=res-5
    checkres(res)
    res=res-4
    checkres(res)
    res=res+18
    checkres(res)
    res=res+13
    checkres(res)
    res=res-6
    checkres(res)
    res=res-3
    checkres(res)
    res=res+8
    checkres(res)
    res=res+2
    checkres(res)
    res=res+12
    checkres(res)
    res=res+2
    checkres(res)
    res=res+17
    checkres(res)
    res=res-4
    checkres(res)
    res=res-16
    checkres(res)
    res=res+15
    checkres(res)
    res=res-8
    checkres(res)
    res=res+1
    checkres(res)
    res=res-11
    checkres(res)
    res=res+2
    checkres(res)
    res=res-15
    checkres(res)
    res=res+21
    checkres(res)
    res=res+1
    checkres(res)
    res=res+5
    checkres(res)
    res=res-16
    checkres(res)
    res=res-4
    checkres(res)
    res=res+22
    checkres(res)
    res=res+17
    checkres(res)
    res=res+17
    checkres(res)
    res=res+7
    checkres(res)
    res=res+6
    checkres(res)
    res=res-16
    checkres(res)
    res=res+5
    checkres(res)
    res=res-10
    checkres(res)
    res=res+17
    checkres(res)
    res=res+6
    checkres(res)
    res=res-14
    checkres(res)
    res=res+7
    checkres(res)
    res=res+12
    checkres(res)
    res=res+3
    checkres(res)
    res=res-11
    checkres(res)
    res=res+6
    checkres(res)
    res=res+4
    checkres(res)
    res=res+19
    checkres(res)
    res=res+10
    checkres(res)
    res=res-12
    checkres(res)
    res=res-10
    checkres(res)
    res=res+1
    checkres(res)
    res=res-16
    checkres(res)
    res=res+19
    checkres(res)
    res=res+4
    checkres(res)
    res=res+11
    checkres(res)
    res=res+13
    checkres(res)
    res=res-14
    checkres(res)
    res=res-2
    checkres(res)
    res=res-13
    checkres(res)
    res=res+8
    checkres(res)
    res=res-13
    checkres(res)
    res=res-11
    checkres(res)
    res=res-18
    checkres(res)
    res=res-5
    checkres(res)
    res=res-15
    checkres(res)
    res=res-7
    checkres(res)
    res=res+10
    checkres(res)
    res=res+14
    checkres(res)
    res=res-1
    checkres(res)
    res=res-12
    checkres(res)
    res=res+9
    checkres(res)
    res=res+12
    checkres(res)
    res=res-18
    checkres(res)
    res=res+14
    checkres(res)
    res=res-27
    checkres(res)
    res=res+17
    checkres(res)
    res=res-5
    checkres(res)
    res=res+2
    checkres(res)
    res=res+33
    checkres(res)
    res=res-2
    checkres(res)
    res=res+25
    checkres(res)
    res=res+14
    checkres(res)
    res=res-6
    checkres(res)
    res=res-1
    checkres(res)
    res=res+15
    checkres(res)
    res=res+1
    checkres(res)
    res=res-8
    checkres(res)
    res=res-13
    checkres(res)
    res=res+9
    checkres(res)
    res=res+7
    checkres(res)
    res=res-26
    checkres(res)
    res=res-6
    checkres(res)
    res=res+26
    checkres(res)
    res=res+8
    checkres(res)
    res=res+10
    checkres(res)
    res=res-5
    checkres(res)
    res=res+18
    checkres(res)
    res=res-5
    checkres(res)
    res=res+14
    checkres(res)
    res=res-11
    checkres(res)
    res=res+6
    checkres(res)
    res=res+28
    checkres(res)
    res=res-40
    checkres(res)
    res=res-6
    checkres(res)
    res=res+8
    checkres(res)
    res=res+12
    checkres(res)
    res=res-5
    checkres(res)
    res=res-23
    checkres(res)
    res=res-8
    checkres(res)
    res=res-3
    checkres(res)
    res=res-21
    checkres(res)
    res=res-43
    checkres(res)
    res=res-9
    checkres(res)
    res=res-5
    checkres(res)
    res=res-9
    checkres(res)
    res=res-16
    checkres(res)
    res=res-16
    checkres(res)
    res=res-13
    checkres(res)
    res=res-3
    checkres(res)
    res=res-4
    checkres(res)
    res=res+13
    checkres(res)
    res=res+12
    checkres(res)
    res=res+1
    checkres(res)
    res=res+16
    checkres(res)
    res=res+21
    checkres(res)
    res=res-1
    checkres(res)
    res=res-8
    checkres(res)
    res=res-24
    checkres(res)
    res=res+14
    checkres(res)
    res=res-21
    checkres(res)
    res=res-6
    checkres(res)
    res=res-7
    checkres(res)
    res=res-19
    checkres(res)
    res=res+3
    checkres(res)
    res=res-4
    checkres(res)
    res=res-14
    checkres(res)
    res=res+8
    checkres(res)
    res=res+8
    checkres(res)
    res=res+10
    checkres(res)
    res=res+7
    checkres(res)
    res=res-10
    checkres(res)
    res=res-12
    checkres(res)
    res=res-13
    checkres(res)
    res=res-13
    checkres(res)
    res=res+11
    checkres(res)
    res=res-13
    checkres(res)
    res=res-10
    checkres(res)
    res=res-7
    checkres(res)
    res=res-9
    checkres(res)
    res=res-18
    checkres(res)
    res=res+13
    checkres(res)
    res=res-4
    checkres(res)
    res=res-20
    checkres(res)
    res=res-7
    checkres(res)
    res=res-4
    checkres(res)
    res=res+9
    checkres(res)
    res=res+1
    checkres(res)
    res=res+13
    checkres(res)
    res=res-11
    checkres(res)
    res=res-10
    checkres(res)
    res=res-10
    checkres(res)
    res=res+4
    checkres(res)
    res=res-6
    checkres(res)
    res=res-5
    checkres(res)
    res=res-19
    checkres(res)
    res=res-14
    checkres(res)
    res=res+1
    checkres(res)
    res=res+1
    checkres(res)
    res=res+10
    checkres(res)
    res=res+10
    checkres(res)
    res=res-14
    checkres(res)
    res=res-11
    checkres(res)
    res=res-13
    checkres(res)
    res=res-11
    checkres(res)
    res=res-12
    checkres(res)
    res=res-11
    checkres(res)
    res=res-7
    checkres(res)
    res=res-13
    checkres(res)
    res=res+22
    checkres(res)
    res=res+31
    checkres(res)
    res=res+6
    checkres(res)
    res=res-1
    checkres(res)
    res=res+42
    checkres(res)
    res=res+21
    checkres(res)
    res=res+11
    checkres(res)
    res=res+5
    checkres(res)
    res=res+10
    checkres(res)
    res=res+1
    checkres(res)
    res=res+2
    checkres(res)
    res=res+20
    checkres(res)
    res=res+10
    checkres(res)
    res=res-14
    checkres(res)
    res=res-1
    checkres(res)
    res=res-8
    checkres(res)
    res=res+2
    checkres(res)
    res=res+19
    checkres(res)
    res=res+26
    checkres(res)
    res=res-14
    checkres(res)
    res=res-2
    checkres(res)
    res=res-1
    checkres(res)
    res=res+2
    checkres(res)
    res=res-20
    checkres(res)
    res=res+13
    checkres(res)
    res=res+25
    checkres(res)
    res=res-15
    checkres(res)
    res=res+14
    checkres(res)
    res=res+33
    checkres(res)
    res=res-3
    checkres(res)
    res=res+7
    checkres(res)
    res=res+20
    checkres(res)
    res=res+12
    checkres(res)
    res=res+14
    checkres(res)
    res=res-7
    checkres(res)
    res=res+36
    checkres(res)
    res=res-2
    checkres(res)
    res=res+7
    checkres(res)
    res=res+71
    checkres(res)
    res=res+30
    checkres(res)
    res=res-16
    checkres(res)
    res=res-4
    checkres(res)
    res=res+69
    checkres(res)
    res=res-15
    checkres(res)
    res=res-32
    checkres(res)
    res=res+203
    checkres(res)
    res=res-7
    checkres(res)
    res=res-6
    checkres(res)
    res=res-4
    checkres(res)
    res=res-5
    checkres(res)
    res=res-20
    checkres(res)
    res=res-28
    checkres(res)
    res=res-21
    checkres(res)
    res=res-21
    checkres(res)
    res=res+18
    checkres(res)
    res=res+183
    checkres(res)
    res=res+22
    checkres(res)
    res=res+11
    checkres(res)
    res=res+16
    checkres(res)
    res=res+2
    checkres(res)
    res=res-31
    checkres(res)
    res=res-28
    checkres(res)
    res=res+21
    checkres(res)
    res=res-61
    checkres(res)
    res=res-104
    checkres(res)
    res=res+7
    checkres(res)
    res=res+50
    checkres(res)
    res=res-58
    checkres(res)
    res=res+178
    checkres(res)
    res=res-89
    checkres(res)
    res=res+68771
    checkres(res)
    res=res-13
    checkres(res)
    res=res-18
    checkres(res)
    res=res+6
    checkres(res)
    res=res-4
    checkres(res)
    res=res-9
    checkres(res)
    res=res+17
    checkres(res)
    res=res+13
    checkres(res)
    res=res-7
    checkres(res)
    res=res+1
    checkres(res)
    res=res+19
    checkres(res)
    res=res+19
    checkres(res)
    res=res+12
    checkres(res)
    res=res+1
    checkres(res)
    res=res+12
    checkres(res)
    res=res+18
    checkres(res)
    res=res-6
    checkres(res)
    res=res-7
    checkres(res)
    res=res+18
    checkres(res)
    res=res-19
    checkres(res)
    res=res+13
    checkres(res)
    res=res+10
    checkres(res)
    res=res+6
    checkres(res)
    res=res+9
    checkres(res)
    res=res+3
    checkres(res)
    res=res-19
    checkres(res)
    res=res-16
    checkres(res)
    res=res-14
    checkres(res)
    res=res+19
    checkres(res)
    res=res+14
    checkres(res)
    res=res-15
    checkres(res)
    res=res-8
    checkres(res)
    res=res-9
    checkres(res)
    res=res-12
    checkres(res)
    res=res+14
    checkres(res)
    res=res+20
    checkres(res)
    res=res-3
    checkres(res)
    res=res-14
    checkres(res)
    res=res-16
    checkres(res)
    res=res-13
    checkres(res)
    res=res-2
    checkres(res)
    res=res-10
    checkres(res)
    res=res-12
    checkres(res)
    res=res+11
    checkres(res)
    res=res+10
    checkres(res)
    res=res+11
    checkres(res)
    res=res+1
    checkres(res)
    res=res+13
    checkres(res)
    res=res-1
    checkres(res)
    res=res-1
    checkres(res)
    res=res+5
    checkres(res)
    res=res-19
    checkres(res)
    res=res-14
    checkres(res)
    res=res+3
    checkres(res)
    res=res-9
    checkres(res)
    res=res-17
    checkres(res)
    res=res+4
    checkres(res)
    res=res+18
    checkres(res)
    res=res-7
    checkres(res)
    res=res-3
    checkres(res)
    res=res+13
    checkres(res)
    res=res+7
    checkres(res)
    res=res+2
    checkres(res)
    res=res+8
    checkres(res)
    res=res-22
    checkres(res)
    res=res+21
    checkres(res)
    res=res+8
    checkres(res)
    res=res-1
    checkres(res)
    res=res-13
    checkres(res)
    res=res+24
    checkres(res)
    res=res+19
    checkres(res)
    res=res+16
    checkres(res)
    res=res+1
    checkres(res)
    res=res-13
    checkres(res)
    res=res+15
    checkres(res)
    res=res+8
    checkres(res)
    res=res+17
    checkres(res)
    res=res+5
    checkres(res)
    res=res+2
    checkres(res)
    res=res+16
    checkres(res)
    res=res+7
    checkres(res)
    res=res-11
    checkres(res)
    res=res+14
    checkres(res)
    res=res-18
    checkres(res)
    res=res-1
    checkres(res)
    res=res-16
    checkres(res)
    res=res-8
    checkres(res)
    res=res+4
    checkres(res)
    res=res-12
    checkres(res)
    res=res+13
    checkres(res)
    res=res+13
    checkres(res)
    res=res-15
    checkres(res)
    res=res-16
    checkres(res)
    res=res-13
    checkres(res)
    res=res+3
    checkres(res)
    res=res+9
    checkres(res)
    res=res-5
    checkres(res)
    res=res-14
    checkres(res)
    res=res+4
    checkres(res)
    res=res+13
    checkres(res)
    res=res+17
    checkres(res)
    res=res+8
    checkres(res)
    res=res-2
    checkres(res)
    res=res-12
    checkres(res)
    res=res+7
    checkres(res)
    res=res+19
    checkres(res)
    res=res-15
    checkres(res)
    res=res+13
    checkres(res)
    res=res-5
    checkres(res)
    res=res+6
    checkres(res)
    res=res+10
    checkres(res)
    res=res+8
    checkres(res)
    res=res-6
    checkres(res)
    res=res-21
    checkres(res)
    res=res+15
    checkres(res)
    res=res+18
    checkres(res)
    res=res+19
    checkres(res)
    res=res-5
    checkres(res)
    res=res-1
    checkres(res)
    res=res+3
    checkres(res)
    res=res+15
    checkres(res)
    res=res-8
    checkres(res)
    res=res+13
    checkres(res)
    res=res+5
    checkres(res)
    res=res-1
    checkres(res)
    res=res+8
    checkres(res)
    res=res+12
    checkres(res)
    res=res-14
    checkres(res)
    res=res-17
    checkres(res)
    res=res-11
    checkres(res)
    res=res+19
    checkres(res)
    res=res-4
    checkres(res)
    res=res-23
    checkres(res)
    res=res-18
    checkres(res)
    res=res+5
    checkres(res)
    res=res-2
    checkres(res)
    res=res+7
    checkres(res)
    res=res+15
    checkres(res)
    res=res-19
    checkres(res)
    res=res+14
    checkres(res)
    res=res-3
    checkres(res)
    res=res-2
    checkres(res)
    res=res-14
    checkres(res)
    res=res+18
    checkres(res)
    res=res+9
    checkres(res)
    res=res-5
    checkres(res)
    res=res-12
    checkres(res)
    res=res+19
    checkres(res)
    res=res+2
    checkres(res)
    res=res+20
    checkres(res)
    res=res+10
    checkres(res)
    res=res-1
    checkres(res)
    res=res-15
    checkres(res)
    res=res-8
    checkres(res)
    res=res+15
    checkres(res)
    res=res+11
    checkres(res)
    res=res+7
    checkres(res)
    res=res-16
    checkres(res)
    res=res+10
    checkres(res)
    res=res+12
    checkres(res)
    res=res+4
    checkres(res)
    res=res-15
    checkres(res)
    res=res+12
    checkres(res)
    res=res+9
    checkres(res)
    res=res+4
    checkres(res)
    res=res+14
    checkres(res)
    res=res-4
    checkres(res)
    res=res-3
    checkres(res)
    res=res-5
    checkres(res)
    res=res+4
    checkres(res)
    res=res-14
    checkres(res)
    res=res-1
    checkres(res)
    res=res-13
    checkres(res)
    res=res+7
    checkres(res)
    res=res-19
    checkres(res)
    res=res+3
    checkres(res)
    res=res+20
    checkres(res)
    res=res+6
    checkres(res)
    res=res-1
    checkres(res)
    res=res+18
    checkres(res)
    res=res+13
    checkres(res)
    res=res-16
    checkres(res)
    res=res-8
    checkres(res)
    res=res+15
    checkres(res)
    res=res+18
    checkres(res)
    res=res-7
    checkres(res)
    res=res-4
    checkres(res)
    res=res-19
    checkres(res)
    res=res+14
    checkres(res)
    res=res-3
    checkres(res)
    res=res+5
    checkres(res)
    res=res+11
    checkres(res)
    res=res+20
    checkres(res)
    res=res-4
    checkres(res)
    res=res+10
    checkres(res)
    res=res-11
    checkres(res)
    res=res+13
    checkres(res)
    res=res+4
    checkres(res)
    res=res-2
    checkres(res)
    res=res-18
    checkres(res)
    res=res+6
    checkres(res)
    res=res+19
    checkres(res)
    res=res-13
    checkres(res)
    res=res+15
    checkres(res)
    res=res+11
    checkres(res)
    res=res+1
    checkres(res)
    res=res+1
    checkres(res)
    res=res+13
    checkres(res)
    res=res+19
    checkres(res)
    res=res+14
    checkres(res)
    res=res-8
    checkres(res)
    res=res-4
    checkres(res)
    res=res+17
    checkres(res)
    res=res-12
    checkres(res)
    res=res+8
    checkres(res)
    res=res+7
    checkres(res)
    res=res+9
    checkres(res)
    res=res+2
    checkres(res)
    res=res-16
    checkres(res)
    res=res-5
    checkres(res)
    res=res+13
    checkres(res)
    res=res+10
    checkres(res)
    res=res-8
    checkres(res)
    res=res-16
    checkres(res)
    res=res+12
    checkres(res)
    res=res-20
    checkres(res)
    res=res-15
    checkres(res)
    res=res+8
    checkres(res)
    res=res+14
    checkres(res)
    res=res+10
    checkres(res)
    res=res-16
    checkres(res)
    res=res-10
    checkres(res)
    res=res-20
    checkres(res)
    res=res-9
    checkres(res)
    res=res-11
    checkres(res)
    res=res+8
    checkres(res)
    res=res+8
    checkres(res)
    res=res+13
    checkres(res)
    res=res-6
    checkres(res)
    res=res+3
    checkres(res)
    res=res+2
    checkres(res)
    res=res+11
    checkres(res)
    res=res-18
    checkres(res)
    res=res+9
    checkres(res)
    res=res+7
    checkres(res)
    res=res-2
    checkres(res)
    res=res+1
    checkres(res)
    res=res+18
    checkres(res)
    res=res-9
    checkres(res)
    res=res+19
    checkres(res)
    res=res+10
    checkres(res)
    res=res-15
    checkres(res)
    res=res+3
    checkres(res)
    res=res+14
    checkres(res)
    res=res+19
    checkres(res)
    res=res-8
    checkres(res)
    res=res+3
    checkres(res)
    res=res+17
    checkres(res)
    res=res-7
    checkres(res)
    res=res-11
    checkres(res)
    res=res+7
    checkres(res)
    res=res+3
    checkres(res)
    res=res-19
    checkres(res)
    res=res+17
    checkres(res)
    res=res+19
    checkres(res)
    res=res+9
    checkres(res)
    res=res+10
    checkres(res)
    res=res+8
    checkres(res)
    res=res-14
    checkres(res)
    res=res-6
    checkres(res)
    res=res-18
    checkres(res)
    res=res+10
    checkres(res)
    res=res+15
    checkres(res)
    res=res-10
    checkres(res)
    res=res-1
    checkres(res)
    res=res-13
    checkres(res)
    res=res-4
    checkres(res)
    res=res+20
    checkres(res)
    res=res-14
    checkres(res)
    res=res+18
    checkres(res)
    res=res+18
    checkres(res)
    res=res+1
    checkres(res)
    res=res+1
    checkres(res)
    res=res+11
    checkres(res)
    res=res+14
    checkres(res)
    res=res+18
    checkres(res)
    res=res+4
    checkres(res)
    res=res-18
    checkres(res)
    res=res+13
    checkres(res)
    res=res+3
    checkres(res)
    res=res+13
    checkres(res)
    res=res+9
    checkres(res)
    res=res-6
    checkres(res)
    res=res+8
    checkres(res)
    res=res-7
    checkres(res)
    res=res-9
    checkres(res)
    res=res+2
    checkres(res)
    res=res-24
    checkres(res)
    res=res-3
    checkres(res)
    res=res+9
    checkres(res)
    res=res+9
    checkres(res)
    res=res-14
    checkres(res)
    res=res-8
    checkres(res)
    res=res-7
    checkres(res)
    res=res-1
    checkres(res)
    res=res-3
    checkres(res)
    res=res-7
    checkres(res)
    res=res-19
    checkres(res)
    res=res-2
    checkres(res)
    res=res-19
    checkres(res)
    res=res+5
    checkres(res)
    res=res-6
    checkres(res)
    res=res-10
    checkres(res)
    res=res+8
    checkres(res)
    res=res-16
    checkres(res)
    res=res-23
    checkres(res)
    res=res+14
    checkres(res)
    res=res+30
    checkres(res)
    res=res+7
    checkres(res)
    res=res+20
    checkres(res)
    res=res+17
    checkres(res)
    res=res-3
    checkres(res)
    res=res+10
    checkres(res)
    res=res-9
    checkres(res)
    res=res+12
    checkres(res)
    res=res+19
    checkres(res)
    res=res-18
    checkres(res)
    res=res-3
    checkres(res)
    res=res+19
    checkres(res)
    res=res-9
    checkres(res)
    res=res-15
    checkres(res)
    res=res+6
    checkres(res)
    res=res-7
    checkres(res)
    res=res+21
    checkres(res)
    res=res-9
    checkres(res)
    res=res-8
    checkres(res)
    res=res-11
    checkres(res)
    res=res-13
    checkres(res)
    res=res-4
    checkres(res)
    res=res+18
    checkres(res)
    res=res-6
    checkres(res)
    res=res-1
    checkres(res)
    res=res-13
    checkres(res)
    res=res+17
    checkres(res)
    res=res-2
    checkres(res)
    res=res-7
    checkres(res)
    res=res+8
    checkres(res)
    res=res-18
    checkres(res)
    res=res-19
    checkres(res)
    res=res+24
    checkres(res)
    res=res-13
    checkres(res)
    res=res+4
    checkres(res)
    res=res-36
    checkres(res)
    res=res-17
    checkres(res)
    res=res+7
    checkres(res)
    res=res-4
    checkres(res)
    res=res-6
    checkres(res)
    res=res-21
    checkres(res)
    res=res+4
    checkres(res)
    res=res-17
    checkres(res)
    res=res+6
    checkres(res)
    res=res-26
    checkres(res)
    res=res+13
    checkres(res)
    res=res-7
    checkres(res)
    res=res-17
    checkres(res)
    res=res+10
    checkres(res)
    res=res-7
    checkres(res)
    res=res+12
    checkres(res)
    res=res-18
    checkres(res)
    res=res-17
    checkres(res)
    res=res-3
    checkres(res)
    res=res+12
    checkres(res)
    res=res-15
    checkres(res)
    res=res-12
    checkres(res)
    res=res+3
    checkres(res)
    res=res-12
    checkres(res)
    res=res+19
    checkres(res)
    res=res-20
    checkres(res)
    res=res+5
    checkres(res)
    res=res+4
    checkres(res)
    res=res+8
    checkres(res)
    res=res-15
    checkres(res)
    res=res+14
    checkres(res)
    res=res-20
    checkres(res)
    res=res+18
    checkres(res)
    res=res+18
    checkres(res)
    res=res+15
    checkres(res)
    res=res-8
    checkres(res)
    res=res-1
    checkres(res)
    res=res-12
    checkres(res)
    res=res+17
    checkres(res)
    res=res+17
    checkres(res)
    res=res+13
    checkres(res)
    res=res+15
    checkres(res)
    res=res+20
    checkres(res)
    res=res+21
    checkres(res)
    res=res+16
    checkres(res)
    res=res-21
    checkres(res)
    res=res+11
    checkres(res)
    res=res-8
    checkres(res)
    res=res+24
    checkres(res)
    res=res-7
    checkres(res)
    res=res-5
    checkres(res)
    res=res-7
    checkres(res)
    res=res+36
    checkres(res)
    res=res+12
    checkres(res)
    res=res-1
    checkres(res)
    res=res-20
    checkres(res)
    res=res+66
    checkres(res)
    res=res-5
    checkres(res)
    res=res+16
    checkres(res)
    res=res+5
    checkres(res)
    res=res+5
    checkres(res)
    res=res-11
    checkres(res)
    res=res+24
    checkres(res)
    res=res+14
    checkres(res)
    res=res-9
    checkres(res)
    res=res-13
    checkres(res)
    res=res+39
    checkres(res)
    res=res-11
    checkres(res)
    res=res-26
    checkres(res)
    res=res+14
    checkres(res)
    res=res+14
    checkres(res)
    res=res-11
    checkres(res)
    res=res+44
    checkres(res)
    res=res-4
    checkres(res)
    res=res-2
    checkres(res)
    res=res+15
    checkres(res)
    res=res+12
    checkres(res)
    res=res-4
    checkres(res)
    res=res+2
    checkres(res)
    res=res+21
    checkres(res)
    res=res+17
    checkres(res)
    res=res-22
    checkres(res)
    res=res+2
    checkres(res)
    res=res+17
    checkres(res)
    res=res+15
    checkres(res)
    res=res+7
    checkres(res)
    res=res+17
    checkres(res)
    res=res+13
    checkres(res)
    res=res+7
    checkres(res)
    res=res+14
    checkres(res)
    res=res+9
    checkres(res)
    res=res-12
    checkres(res)
    res=res-7
    checkres(res)
    res=res+23
    checkres(res)
    res=res+7
    checkres(res)
    res=res+4
    checkres(res)
    res=res-16
    checkres(res)
    res=res-23
    checkres(res)
    res=res+16
    checkres(res)
    res=res+21
    checkres(res)
    res=res+3
    checkres(res)
    res=res+13
    checkres(res)
    res=res-4
    checkres(res)
    res=res+6
    checkres(res)
    res=res+18
    checkres(res)
    res=res-19
    checkres(res)
    res=res+5
    checkres(res)
    res=res+10
    checkres(res)
    res=res-25
    checkres(res)
    res=res+23
    checkres(res)
    res=res+11
    checkres(res)
    res=res+14
    checkres(res)
    res=res-1
    checkres(res)
    res=res-14
    checkres(res)
    res=res+19
    checkres(res)
    res=res+22
    checkres(res)
    res=res+2
    checkres(res)
    res=res+8
    checkres(res)
    res=res+22
    checkres(res)
    res=res+18
    checkres(res)
    res=res-38
    checkres(res)
    res=res+4
    checkres(res)
    res=res-20
    checkres(res)
    res=res-26
    checkres(res)
    res=res+20
    checkres(res)
    res=res-13
    checkres(res)
    res=res-20
    checkres(res)
    res=res-11
    checkres(res)
    res=res-3
    checkres(res)
    res=res-23
    checkres(res)
    res=res-31
    checkres(res)
    res=res-8
    checkres(res)
    res=res-1
    checkres(res)
    res=res+10
    checkres(res)
    res=res-31
    checkres(res)
    res=res-3
    checkres(res)
    res=res-22
    checkres(res)
    res=res-11
    checkres(res)
    res=res+19
    checkres(res)
    res=res+18
    checkres(res)
    res=res+1
    checkres(res)
    res=res-23
    checkres(res)
    res=res-5
    checkres(res)
    res=res-33
    checkres(res)
    res=res+8
    checkres(res)
    res=res-7
    checkres(res)
    res=res-33
    checkres(res)
    res=res-3
    checkres(res)
    res=res+44
    checkres(res)
    res=res-60
    checkres(res)
    res=res+11
    checkres(res)
    res=res+85
    checkres(res)
    res=res+177
    checkres(res)
    res=res+18
    checkres(res)
    res=res-126
    checkres(res)
    res=res+50
    checkres(res)
    res=res+128
    checkres(res)
    res=res-44
    checkres(res)
    res=res+68095
    checkres(res)
    res=res-7
    checkres(res)
    res=res-6
    checkres(res)
    res=res-17
    checkres(res)
    res=res-18
    checkres(res)
    res=res-137490
    checkres(res)
